baseurl = "/"
title = "Riserr Code"
theme = "ghostwriter"

[Params]
    mainSections = ["post"]
    intro = true
    headline = "Riserr Code"
    description = "Actively building project as a developer to continuosly train my skill on this field"
    github = "https://github.com/Riserr"
    twitter = "https://twitter.com/XXX"
    email = "XXX@example.com"
    opengraph = true
    shareTwitter = true
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:filename/"